FROM php:7.4.16-apache

RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf \
\
    &&  apt-get update \
    &&  apt-get install -y --no-install-recommends \
        locales apt-utils git libicu-dev g++ libpng-dev libxml2-dev libzip-dev libonig-dev libxslt-dev libpq-dev \
        unixodbc unixodbc-dev tdsodbc postgresql postgresql-contrib unzip nodejs npm vim zsh \
\
    &&  curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh \
    &&  echo "en_US.UTF-8 UTF-8" > /etc/locale.gen  \
    &&  echo "fr_FR.UTF-8 UTF-8" >> /etc/locale.gen \
    &&  locale-gen \
\
    &&  curl -sS https://getcomposer.org/installer | php -- \
    &&  mv composer.phar /usr/local/bin/composer \
    &&  npm install --global yarn
\
    &&  curl -sS https://get.symfony.com/cli/installer | bash \
    &&  mv /root/.symfony/bin/symfony /usr/local/bin \
\
    &&  docker-php-ext-configure intl \
    &&  docker-php-ext-configure pdo_odbc --with-pdo-odbc=unixODBC,/usr/\
    &&  docker-php-ext-install \
            pgsql pdo_pgsql pdo pdo_mysql pdo_odbc opcache intl zip calendar dom mbstring gd xsl \
\
    &&  pecl install apcu && docker-php-ext-enable apcu

WORKDIR /var/www