version: '3.8'
services:
    psql:
        image: postgres
        container_name: db_docker_srvp
        restart: 'no'
        volumes:
            - ./docker/db:/var/lib/psql
        environment:
            POSTGRES_DB: docker_srvp_db
            POSTGRES_USER: docker_db
            POSTGRES_PASSWORD: docker_db
        networks:
            - dev

    pgadmin4:
        image: dpage/pgadmin4
        container_name: docker_srvp_pgadmin
        environment:
          PGADMIN_DEFAULT_PASSWORD: root
          PGADMIN_DEFAULT_EMAIL: votre_email
        ports:
            - 8741:80
        links:
            - psql
        networks:
            - dev
    php:
        build: docker/php
        container_name: docker_srvp_apache_php
        ports:
            - "8080:80"
        volumes:
          - ./docker/php/vhosts:/etc/apache2/sites-enabled
          - ./:/var/www
        restart: 'no'
        networks:
          - dev

networks:
    dev:
